#!/bin/bash
#init led & button

CARD_NAME='wm8960soundcard'


echo 25 >/sys/class/gpio/export
echo out >/sys/class/gpio/gpio25/direction
echo 23 >/sys/class/gpio/export
echo in >/sys/class/gpio/gpio23/direction
#infinite loop
while [ 1 ]
do
error=0


echo  "-----> Test for Raspiaudio MIC ULTRA++"
echo  "------Please push on the Yellow button to test"
cd /home/rosco/ULTRAtest/

#testing speaker L speaker
#sudo alsactl store
#SET Config for speaker out ---start

amixer -c "$CARD_NAME" sset 'Headphone Playback Volume' 80%

amixer -c "$CARD_NAME" sset "Headphone" 200
amixer -c "$CARD_NAME" sset "Headphone Playback ZC" off
amixer -c "$CARD_NAME" sset "Speaker" 120
amixer -c "$CARD_NAME" sset "Speaker AC" 5
amixer -c "$CARD_NAME" sset "Speaker DC" 5
amixer -c "$CARD_NAME" sset "Speaker Playback ZC" off
amixer -c "$CARD_NAME" -c "$CARD_NAME" sset "PCM Playback -6dB" off
amixer -c "$CARD_NAME" sset "Mono Output Mixer Left" off
amixer -c "$CARD_NAME" sset "Mono Output Mixer Right" off
amixer -c "$CARD_NAME" sset "Playback" 240
amixer -c "$CARD_NAME" sset "Capture" 0
amixer -c "$CARD_NAME" sset "3D" 0
amixer -c "$CARD_NAME" sset "3D Filter Lower Cut-Off" Low
amixer -c "$CARD_NAME" sset "3D Filter Upper Cut-Off" off
amixer -c "$CARD_NAME" sset "ADC Data Output Select" "Left Data = Left ADC; Right Data = Right ADC"
amixer -c "$CARD_NAME" sset "ADC High Pass Filter" off
amixer -c "$CARD_NAME" sset "ADC PCM" 190
amixer -c "$CARD_NAME" sset "ADC Polarity" "No Inversion"
amixer -c "$CARD_NAME" sset "ALC Attack" 0
amixer -c "$CARD_NAME" sset "ALC Decay" 0
amixer -c "$CARD_NAME" sset "ALC Function" "Off"
amixer -c "$CARD_NAME" sset "ALC Hold Time" 0
amixer -c "$CARD_NAME" sset "ALC Max Gain" 0
amixer -c "$CARD_NAME" sset "ALC Min Gain" 0
amixer -c "$CARD_NAME" sset "ALC Mode" "ALC"
amixer -c "$CARD_NAME" sset "ALC Target" 0
amixer -c "$CARD_NAME" sset "DAC Deemphasis" off
amixer -c "$CARD_NAME" sset "DAC Mono Mix" "Stereo"
amixer -c "$CARD_NAME" sset "DAC Polarity" "No Inversion"
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT1" on
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT2" off
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT3" off
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT1" 100
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT2" 0
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT3" 0
amixer -c "$CARD_NAME" sset "Left Input Mixer Boost" on
amixer -c "$CARD_NAME" sset "Left Output Mixer Boost Bypass" 0
amixer -c "$CARD_NAME" sset "Left Output Mixer LINPUT3" 0
amixer -c "$CARD_NAME" sset "Left Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Noise Gate" off
amixer -c "$CARD_NAME" sset "Noise Gate Threshold" 0
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT1" on
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT2" off
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT3" off
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT1" 100
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT2" 0
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT3" 0
amixer -c "$CARD_NAME" sset "Right Input Mixer Boost" on
amixer -c "$CARD_NAME" sset "Right Output Mixer Boost Bypass" 0
amixer -c "$CARD_NAME" sset "Right Output Mixer PCM" off
amixer -c "$CARD_NAME" sset "Right Output Mixer RINPUT3" 0
amixer -c "$CARD_NAME" sset "Capture" 25 

#SET Config for speaker out ---stop
echo "SET Config for speaker out "
#led ON
echo 1 >/sys/class/gpio/gpio25/value


#waiting button pressed
while [ `cat /sys/class/gpio/gpio23/value` = 1 ]; do
set i = 1
done

rm result.txt

#led OFF
echo 0 >/sys/class/gpio/gpio25/value
#record 5s


arecord -d3 -r 16000 recorded456.wav&
sleep 1
aplay dtmf_456.wav
sleep 2


tmp=`multimon-ng -a DTMF -t wav recorded456.wav -q | uniq`
tmp="${tmp//DTMF: }"
tmp="${tmp//[$'\t\r\n']}"

echo $tmp

if [ "$tmp" == "456" ]; then
    echo "test Left speaker passed" >> result.txt
else
    echo "test Left speaker failed" >> result.txt
    error=$((error+1))

fi





#test speaker R
amixer -c "$CARD_NAME" sset "Left Output Mixer PCM" off
amixer -c "$CARD_NAME" sset "Right Output Mixer PCM" on


arecord -d3 -r 16000 recorded456.wav&
sleep 1
aplay dtmf_456.wav
sleep 2

tmp=`multimon-ng -a DTMF -t wav recorded456.wav -q | uniq`
tmp="${tmp//DTMF: }"
tmp="${tmp//[$'\t\r\n']}"
echo $tmp

if [ "$tmp" == "456" ]; then
    echo "test Right speaker passed" >> result.txt
else
    echo "test Right speaker failed" >> result.txt
	error=$((error+2))

fi




#test onboar MIC L
amixer -c "$CARD_NAME" sset "Left Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Right Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT1" 120
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT1" 0


arecord -d3 -r 16000 recorded456.wav&
sleep 1
aplay dtmf_456.wav
sleep 2

tmp=`multimon-ng -a DTMF -t wav recorded456.wav -q | uniq`
tmp="${tmp//DTMF: }"
tmp="${tmp//[$'\t\r\n']}"
echo $tmp

if [ "$tmp" == "456" ]; then
    echo "test onboard MIC L passed" >> result.txt
else
    echo "test onboard MIC L failed" >> result.txt
error=$((error+4))

fi




#test onboard MIC R
amixer -c "$CARD_NAME" sset "Left Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Right Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT1" 0
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT1" 100


arecord -d3 -r 16000 recorded456.wav&
sleep 1
aplay dtmf_456.wav
sleep 2

tmp=`multimon-ng -a DTMF -t wav recorded456.wav -q | uniq`
tmp="${tmp//DTMF: }"
tmp="${tmp//[$'\t\r\n']}"
echo $tmp

if [ "$tmp" == "456" ]; then
    echo "test onboard MIC R passed" >> result.txt
else
    echo "test onboard MIC R failed" >> result.txt
error=$((error+8))

fi




#test LINE R


bash MicUltra_Input_Line_Input3


amixer -c "$CARD_NAME" sset "Headphone" 140
amixer -c "$CARD_NAME" sset "Speaker" 115
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT1" off
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT2" off
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT3" off
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT1" 0
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT2" 0
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT3" 0
#amixer -c "$CARD_NAME" sset "Left Output Mixer PCM" off
#amixer -c "$CARD_NAME" sset "Left Input Mixer Boost" off

amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT1" off
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT2" off
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT3" on
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT1" 0
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT2" 0
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT3" 7
#amixer -c "$CARD_NAME" sset "Right Output Mixer PCM" on
#amixer -c "$CARD_NAME" sset "Right Input Mixer Boost" on
#amixer -c "$CARD_NAME" sset "Left Output Mixer PCM" on


arecord -d3 -r 16000 recorded456.wav&
sleep 1
aplay dtmf_456.wav
sleep 2


tmp=`multimon-ng -a DTMF -t wav recorded456.wav -q | uniq`
tmp="${tmp//DTMF: }"
tmp="${tmp//[$'\t\r\n']}"
echo $tmp

if [ "$tmp" == "456" ]; then
    echo "test external LINE R passed" >> result.txt
else
    echo "test external LINE R failed" >> result.txt
	error=$((error+16))

fi




#test LINE L
amixer -c "$CARD_NAME" sset "Headphone" 125
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT1" off
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT2" off
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT3" on
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT1" 0
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT2" 0
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT3" 7
amixer -c "$CARD_NAME" sset "Left Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Left Input Mixer Boost" on

amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT1" off
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT2" off
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT3" off
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT1" 0
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT2" 0
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT3" 0
amixer -c "$CARD_NAME" sset "Right Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Left Input Mixer Boost" off


arecord -d3 -r 16000 recorded456.wav&
sleep 1
aplay dtmf_456.wav
sleep 2




tmp=`multimon-ng -a DTMF -t wav recorded456.wav -q | uniq`
tmp="${tmp//DTMF: }"
tmp="${tmp//[$'\t\r\n']}"
echo $tmp

if [ "$tmp" == "456" ]; then
    echo "test external LINE L passed" >> result.txt
else
    echo "test external LINE L failed" >> result.txt
error=$((error+32))

fi




#-------------------------


amixer -c "$CARD_NAME" sset "Headphone" 100
amixer -c "$CARD_NAME" sset "Headphone Playback ZC" off
amixer -c "$CARD_NAME" sset "Speaker" 130
amixer -c "$CARD_NAME" sset "Speaker AC" 5
amixer -c "$CARD_NAME" sset "Speaker DC" 5
amixer -c "$CARD_NAME" sset "Speaker Playback ZC" off
amixer -c "$CARD_NAME" sset "PCM Playback -6dB" off
amixer -c "$CARD_NAME" sset "Mono Output Mixer Left" off
amixer -c "$CARD_NAME" sset "Mono Output Mixer Right" off
amixer -c "$CARD_NAME" sset "Playback" 230
amixer -c "$CARD_NAME" sset "Capture" 0
amixer -c "$CARD_NAME" sset "3D" 0
amixer -c "$CARD_NAME" sset "3D Filter Lower Cut-Off" Low
amixer -c "$CARD_NAME" sset "3D Filter Upper Cut-Off" off
amixer -c "$CARD_NAME" sset "ADC Data Output Select" "Left Data = Left ADC; Right Data = Right ADC"
amixer -c "$CARD_NAME" sset "ADC High Pass Filter" off
amixer -c "$CARD_NAME" sset "ADC PCM" 230
amixer -c "$CARD_NAME" sset "ADC Polarity" "No Inversion"
amixer -c "$CARD_NAME" sset "ALC Attack" 0
amixer -c "$CARD_NAME" sset "ALC Decay" 0
amixer -c "$CARD_NAME" sset "ALC Function" "Off"
amixer -c "$CARD_NAME" sset "ALC Hold Time" 0
amixer -c "$CARD_NAME" sset "ALC Max Gain" 0
amixer -c "$CARD_NAME" sset "ALC Min Gain" 0
amixer -c "$CARD_NAME" sset "ALC Mode" "ALC"
amixer -c "$CARD_NAME" sset "ALC Target" 0
amixer -c "$CARD_NAME" sset "DAC Deemphasis" off
amixer -c "$CARD_NAME" sset "DAC Mono Mix" "Stereo"
amixer -c "$CARD_NAME" sset "DAC Polarity" "No Inversion"
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT1" off
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT2" on
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT3" off
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT1" 0
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT2" 200
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT3" 0
amixer -c "$CARD_NAME" sset "Left Input Mixer Boost" on
amixer -c "$CARD_NAME" sset "Left Output Mixer Boost Bypass" 0
amixer -c "$CARD_NAME" sset "Left Output Mixer LINPUT3" 0
amixer -c "$CARD_NAME" sset "Left Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Noise Gate" off
amixer -c "$CARD_NAME" sset "Noise Gate Threshold" 0
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT1" off
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT2" on
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT3" off
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT1" 0
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT2" 200
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT3" 0
amixer -c "$CARD_NAME" sset "Right Input Mixer Boost" on
amixer -c "$CARD_NAME" sset "Right Output Mixer Boost Bypass" off
amixer -c "$CARD_NAME" sset "Right Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Right Output Mixer RINPUT3" 0
amixer -c "$CARD_NAME" sset "Capture" 40



#test MIC external L
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT1" off
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT2" on
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT3" off
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT1" 0
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT2" 220
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT3" 0
amixer -c "$CARD_NAME" sset "Left Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Left Input Mixer Boost" on

amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT1" off
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT2" off
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT3" off
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT1" 0
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT2" 0
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT3" 0
amixer -c "$CARD_NAME" sset "Right Output Mixer PCM" off
amixer -c "$CARD_NAME" sset "Right Input Mixer Boost" off


arecord -d3 -r 16000 recorded456.wav&
sleep 1
aplay dtmf_456.wav
sleep 2



tmp=`multimon-ng -a DTMF -t wav recorded456.wav -q | uniq`
tmp="${tmp//DTMF: }"
tmp="${tmp//[$'\t\r\n']}"
echo $tmp

if [ "$tmp" == "456" ]; then
    echo "test MIC external L passed" >> result.txt
else
    echo "test MIC external L failed" >> result.txt
error=$((error+64))
	

fi







#test MIC external R
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT1" off
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT2" off
amixer -c "$CARD_NAME" sset "Left Boost Mixer LINPUT3" off
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT1" 0
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT2" 0
amixer -c "$CARD_NAME" sset "Left Input Boost Mixer LINPUT3" 0
amixer -c "$CARD_NAME" sset "Left Output Mixer PCM" off
amixer -c "$CARD_NAME" sset "Left Input Mixer Boost" off

amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT1" off
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT2" on
amixer -c "$CARD_NAME" sset "Right Boost Mixer RINPUT3" off
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT1" 0
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT2" 250
amixer -c "$CARD_NAME" sset "Right Input Boost Mixer RINPUT3" 0
amixer -c "$CARD_NAME" sset "Right Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Right Input Mixer Boost" on


arecord -d3 -r 16000 recorded456.wav&
sleep 1
aplay dtmf_456.wav
sleep 2

tmp=`multimon-ng -a DTMF -t wav recorded456.wav -q | uniq`
tmp="${tmp//DTMF: }"
tmp="${tmp//[$'\t\r\n']}"
echo $tmp

if [ "$tmp" == "456" ]; then
    echo "test MIC external R passed" >> result.txt
else
    echo "test MIC external R failed" >> result.txt
error=$((error+128))

fi



amixer -c "$CARD_NAME" sset "Speaker" 127
amixer -c "$CARD_NAME" sset "Playback" 255
amixer -c "$CARD_NAME" sset "Left Output Mixer PCM" on
amixer -c "$CARD_NAME" sset "Left Input Mixer Boost" on



cat result.txt


if [ "$error" != "0" ]; then
    echo TEST FAILED Error number : $error
	sudo echo "Error number : $error" | festival --tts
	sudo echo "Error number : $error" | festival --tts
else
    echo TEST PASSED!
	sudo echo "TEST PASSED!" | festival --tts

echo 25 >/sys/class/gpio/export
echo out >/sys/class/gpio/gpio25/direction

		while [ 1 ]
		do
			sudo echo 1 >/sys/class/gpio/gpio25/value
			sleep 1
			sudo echo 0 >/sys/class/gpio/gpio25/value
			
		done


fi



done

